spring.application.name=stagingapi
# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/tote_db
***REMOVED***
***REMOVED***
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
